Splitting update-tester into subcommands
timescale/timescaledb-toolkit pull request #486
Opened 2022-08-01 21:00 UTC by thatzopoulos

- Updated to Clap v3 and replaced the deprecated `clap_app!` macro
- Removed `-h` as a shorthand option for `HOST` since it conflicts with the `help` flag
- Added subcommands for the original functionality (`full-update-test-source`), creating test objects (`create-test-objects`), and validating results (`validate-test-objects`).

Differences between original functionality and the `create-test-objects`/`validate-test-objects` subcommands:
- The alter/create extension commands no longer use a specific version of the toolkit when called. It is expected that the user manually installs their toolkit versions before running `create-test-objects` and/or `validate-test-objects`.
- The temporary databases created by `full-update-test-source` are named after the version numbers of the toolkit versions that they are testing, but the new subcommands create and expect a database named `tsdb_toolkit_test`.
- The database created by `create-test-objects` is dropped at the end of `validate-test-objects` if the validation tests pass.

2022-08-08 15:46 UTC, epgts reviewed
Looks pretty good now.  I have a few suggestions.  Also, time to un-draft?  Thanks!

2022-08-08 15:46 UTC, epgts commented on tools/build
> +		 full-update-test-source \
nit: indentation is off - probably easiest to fold this into the previous line

2022-08-08 15:46 UTC, epgts commented on tools/update-tester/src/main.rs
> +                ///
stale empty comment?

2022-08-08 15:46 UTC, epgts commented on tools/update-tester/src/testrunner.rs
> +    // client.simple_query(&drop_if_exists).unwrap_or_else(|e| panic!("could not drop db {} due to {}", test_db_name,e));
clean this up?

2022-08-08 15:46 UTC, epgts commented on tools/update-tester/src/testrunner.rs
> +    let validation_results: Vec<Vec<Option<String>>> = vec![vec![
nit: `expected_results` is a common name for this sort of thing

2022-08-08 19:08 UTC, thatzopoulos commented on tools/update-tester/src/main.rs
> +	.get_matches();
That is odd, when I run `sh tools/build test-updates` on my machine it seems to exit with 1.

2022-08-08 19:40 UTC, epgts commented on tools/update-tester/src/main.rs
> +	.get_matches();
You fixed it!

You can reproduce the failure on commit 1b98c89:

cargo run --manifest-path tools/update-tester/Cargo.toml -- -h localhost -p 5432 --cache old-versions . /usr/local/pgsql/bin/pg_config /pgx/0.4/bin/cargo-pgx /pgx/0.2/bin/cargo-pgx

On the latest, it is fixed and now exits 2.

2022-08-08 20:21 UTC, rtwalker approved these changes
Looks good to me!

Do you think it is worth bumping the version in `tools/update-tester/Cargo.toml` with the changes to now require a `<SUBCOMMAND>` to be passed to the `update-tester` command?

2022-08-08 20:21 UTC, rtwalker commented on tools/update-tester/src/testrunner.rs
> +    let expected_results: Vec<Vec<Option<String>>> = vec![vec![
Do you mind moving this to right under the `// run validation tests` line? It took me a couple seconds to figure out where we use this data

2022-08-08 20:21 UTC, rtwalker commented on tools/update-tester/src/main.rs
> +Command::new("create-test-objects").long_flag("create-test-objects")
could you add a quick `.about(...)` here?

2022-08-08 20:21 UTC, rtwalker commented on tools/update-tester/src/main.rs
> +Command::new("validate-test-objects").long_flag("validate-test-objects")
could you add a quick `.about(...)` here?

2022-08-09 18:27 UTC, thatzopoulos commented
> 

That seems like a good idea to me. I will bump it to `0.3.0`

2022-08-09 21:58 UTC, epgts requested changes
Looks good.  Can you squash the 7 into 1 commit and revert the two stabilization files that don't have any real changes in them?  Thanks!

2022-08-09 21:58 UTC, epgts commented on tools/update-tester/src/main.rs
> +Command::new("create-test-objects").long_flag("create-test-objects").about("Creates test objects using the currently installed version of Toolkit")
Can we get some line breaks in here? :)

Indentation and similar problems in other places too.  Probably it all needs a rustfmt.

2022-08-09 21:58 UTC, epgts commented on tools/update-tester/src/main.rs
> +                ///
stray empty comment

2022-08-09 21:58 UTC, epgts commented on tools/update-tester/src/testrunner.rs
> +    let expected_results: Vec<Vec<Option<String>>> = vec![vec![
`QueryValues` (line 179)?  Though I'm not a fan of type alias like that.  I think they obscure rather than clarify.

2022-08-10 18:51 UTC, epgts approved these changes

2022-08-10 19:22 UTC, thatzopoulos commented
bors r+

2022-08-10 19:30 UTC, merged

2022-08-31 01:00 UTC, epgts commented on tools/update-tester/src/testrunner.rs
> +    test_client.validate_test_objects(expected_results);
Sorry I didn't catch it before, @thatzopoulos, but we need these tests here too:

```
            test_client.check_no_references_to_the_old_binary_leaked(&current_version);
            test_client.validate_stable_objects_exist();
```